# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2020-09-28"
# docker_image = "jjy0/ckb-capsule-recipe-rust:2020-9-28"

# capsule version
version = "{{ version }}"
# path of deployment config file
deployment = "deployment.toml"
